const App = (props) => {
  const { notes } = props

  // the list items, i.e. the elements generated by
  // the map method, must each have a unique key
  // value: an attribute called key.
  
  return (
    <div>
      <h1>Notes</h1>
      <ul>
        {notes.map(note =>
        <li key={note.id}>
          {notes.content}
        </li>
      )}
      </ul>
    </div>
  )
}

// React uses the key attributes of objects in an
// array to determine how to update the view
// generated by a component when the component
// is re-rendered.

export default App
